### ISSUE TITLE
$uri->withQuery(Query::createFromUri($uri)) can fail

### ISSUE THREAD

**Issue by arnaud-lb** [thephpleague/uri#202] opened 2022-05-25 13:34 UTC
### Bug Report

| Information | Description |
|--------------|---------|
| Version |  6.5.0 |
| PHP version | 8.1 |
| OS Platform | Linux |

#### Summary

 `Uri::withQuery()` does not accept the URI's original query string after is has been parsed with `Query::createFromUri()`.

#### Standalone code, or other way to reproduce the problem

```
$url = \League\Uri\Uri::createFromString("http://example.com/?foo=" . urlencode("\v\xED"));
$url = $url->withQuery(\League\Uri\Components\Query::createFromUri($url));
echo $url->toString(), "\n";
```

#### Expected result

```
http://example.com/?foo=%0B%ED
```

#### Actual result

```
League\Uri\Exceptions\SyntaxError: The component `foo=
                                                      �` contains invalid characters. in vendor/league/uri/src/Uri.php:1276
Stack trace:
#0 vendor/league/uri/src/Uri.php(1369): League\Uri\Uri->filterString('foo=\v\xED')
#1 test.php(49): League\Uri\Uri->withQuery(Object(League\Uri\Components\Query))
```

**Comment by nyamsprod** [comment] 2022-05-25 19:16
@arnaud-lb thanks for the report. I will investigate it a bit further as this as more implications. Might be a bug or not 🤔 . Either way I already took a note of the issue and found the root cause.
The main issue is not on the URI package but on the URI components one. But I will leave the issue open here and not transfert it to the other package.

**Comment by nyamsprod** [comment] 2022-05-25 20:16
@arnaud-lb a fix has landed on the uri-components package. Please review it and if all is good I will publish the fix next week

**Comment by arnaud-lb** [comment] 2022-05-25 21:26
Awesome, thank you!

The issue also exists in pair names, e.g. 
```
$url = \League\Uri\Uri::createFromString("http://example.com/?".urlencode("\v\xED")."=" . urlencode("\v\xED"));
$url = $url->withQuery(\League\Uri\Components\Query::createFromUri($url));
echo $url->toString(), "\n";
```
can also fail.

Otherwise, I confirm that this fixes the original issue :)

**Comment by nyamsprod** [comment] 2022-05-25 21:32
Will have to look at the pair name then ... issue still not totally fixed but I guess the same fix should be applied there 😉 
Once the named are fixed and the patch updated I will let you know

**Comment by nyamsprod** [comment] 2022-05-25 21:36
@arnaud-lb you are lucky the pair name is now also patch 🎉

**Comment by arnaud-lb** [comment] 2022-05-25 21:40
I confirm :tada: 

Thank you !

**Comment by nyamsprod** [comment] 2022-05-26 05:56
l[eague/uri-components:2.4.1](https://github.com/thephpleague/uri-components/blob/master/CHANGELOG.md#241---2022-05-26) is released with the fix 🔥

**Closed by nyamsprod** 2022-05-26 05:56 UTC
Labels: bug, version 6

**Comment by nyamsprod** [comment] 2022-05-26 06:44
@arnaud-lb as a side note currently uri-components requires PHP7.4 at least while league/uri still supports PHP7.3 when I get time I will drop support for PHP7.3 and *maybe* PHP7 as the whole. I know it is not directly related to your issue but keep that in mind 😉
